#!/bin/bash
# make_app.sh — Build a one-click macOS app bundle (epub2md.app) for this project.
#
# The generated app:
#   • Launches with a single click from the Dock / Applications / Spotlight (no Terminal).
#   • On first run, silently sets up the virtual environment (shows a macOS notification).
#   • Starts the Flask server and opens your browser to http://localhost:3763.
#   • The Dock icon *is* the running server — right-click → Quit stops it cleanly.
#
# Usage:
#   ./make_app.sh                 # build ./epub2md.app, baking in this folder's path
#   ./make_app.sh --install       # also copy it to ~/Applications
#
# If you move this project folder later, just re-run ./make_app.sh to rebuild.

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="epub2md"
APP="$REPO_DIR/$APP_NAME.app"
URL="http://localhost:3763"

# Read the project version (single source of truth) for the bundle metadata.
VERSION="$(sed -n 's/^__version__ = "\(.*\)"/\1/p' "$REPO_DIR/version.py" 2>/dev/null)"
[ -z "$VERSION" ] && VERSION="0.0.0"

echo "Building $APP_NAME.app (v$VERSION)"
echo "  project folder: $REPO_DIR"

# Fresh bundle.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------------------
# Info.plist
# ---------------------------------------------------------------------------
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>$APP_NAME</string>
    <key>CFBundleDisplayName</key><string>$APP_NAME</string>
    <key>CFBundleIdentifier</key><string>net.adamdexter.epub2md</string>
    <key>CFBundleVersion</key><string>$VERSION</string>
    <key>CFBundleShortVersionString</key><string>$VERSION</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleExecutable</key><string>$APP_NAME</string>
    <key>CFBundleIconFile</key><string>$APP_NAME</string>
    <key>LSMinimumSystemVersion</key><string>10.13</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# Launcher executable — baked with the absolute project path.
# ---------------------------------------------------------------------------
cat > "$APP/Contents/MacOS/$APP_NAME" <<LAUNCHER
#!/bin/bash
# epub2md.app launcher — generated by make_app.sh. Edit make_app.sh and rebuild, not this file.
REPO_DIR="$REPO_DIR"
URL="$URL"
LAUNCHER

# Append the launcher body verbatim (no further variable expansion).
cat >> "$APP/Contents/MacOS/$APP_NAME" <<'LAUNCHER'

# Apps launched from Finder inherit a minimal PATH (no Homebrew), which is why a
# GUI launch can't find pandoc even when it's installed. Rebuild a useful PATH,
# including our managed bin dir where the installer may drop brew-free tools.
export PATH="$HOME/Library/Application Support/epub2md/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"
if command -v brew >/dev/null 2>&1; then
    export PATH="$(brew --prefix)/bin:$PATH"
fi

cd "$REPO_DIR" 2>/dev/null || {
    osascript -e "display dialog \"epub2md project folder not found:

$REPO_DIR

If you moved the project, re-run make_app.sh to rebuild this app.\" buttons {\"OK\"} default button \"OK\" with icon stop with title \"epub2md\""
    exit 1
}

# Run setup if the venv is missing/broken OR a required tool isn't on PATH.
# The installer (in --yes mode) auto-installs Python/Pandoc with no prompts.
need_setup=0
[ -x ".venv/bin/python3" ] || need_setup=1
command -v python3 >/dev/null 2>&1 || need_setup=1
command -v pandoc  >/dev/null 2>&1 || need_setup=1

if [ "$need_setup" -eq 1 ]; then
    osascript -e 'display notification "Setting up & installing any missing tools… this can take a few minutes." with title "epub2md"'
    if ! bash ./install.sh --yes >/tmp/epub2md-install.log 2>&1; then
        osascript -e 'display dialog "epub2md setup failed.

See the log at /tmp/epub2md-install.log" buttons {"OK"} default button "OK" with icon stop with title "epub2md"'
        open -t /tmp/epub2md-install.log 2>/dev/null
        exit 1
    fi
    # The installer may have dropped a standalone tool in our managed bin dir.
    export PATH="$HOME/Library/Application Support/epub2md/bin:$PATH"
    osascript -e 'display notification "Setup complete — starting…" with title "epub2md"'
fi

# Safety net: make sure the essentials are actually runnable before we launch.
missing=""
command -v python3 >/dev/null 2>&1 || missing="Python 3"
command -v pandoc  >/dev/null 2>&1 || missing="${missing:+$missing and }Pandoc"
if [ -n "$missing" ] || [ ! -x ".venv/bin/python3" ]; then
    osascript -e "display dialog \"epub2md couldn't finish setting up (${missing:-environment}).

See the log at /tmp/epub2md-install.log\" buttons {\"OK\"} default button \"OK\" with icon stop with title \"epub2md\""
    exit 1
fi

# Pass our bundle icon to the window process so it shows our icon in the Dock and
# Cmd+Tab switcher (the framework Python would otherwise show Python's icon).
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SELF_DIR/../Resources/epub2md.icns" ]; then
    export EPUB2MD_ICNS="$SELF_DIR/../Resources/epub2md.icns"
fi

# Become the app: this one process serves Flask in a background thread and shows
# the UI in a native WebKit window. Closing the window quits and stops the server.
exec ".venv/bin/python3" gui.py --window
LAUNCHER

chmod +x "$APP/Contents/MacOS/$APP_NAME"

# ---------------------------------------------------------------------------
# Icon (best effort). Needs Pillow to draw the master PNG; sips + iconutil
# (always present on macOS) do the rest. If Pillow isn't available yet, the
# app still works with a generic icon — re-run make_app.sh after first launch
# (the venv will have Pillow) to add the real icon.
# ---------------------------------------------------------------------------
make_icon() {
    local py="$1"
    local tmp
    tmp="$(mktemp -d)"
    if ! "$py" - "$tmp/icon_1024.png" <<'PY'
import sys
try:
    from PIL import Image, ImageDraw, ImageFont
except Exception:
    sys.exit(3)

out = sys.argv[1]
S = 1024
img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
d = ImageDraw.Draw(img)

# Rounded-rect background with a simple vertical gradient.
radius = int(S * 0.22)
top, bot = (37, 99, 235), (29, 78, 216)  # blue
grad = Image.new("RGBA", (S, S), top + (255,))
gd = ImageDraw.Draw(grad)
for y in range(S):
    t = y / S
    r = int(top[0] * (1 - t) + bot[0] * t)
    g = int(top[1] * (1 - t) + bot[1] * t)
    b = int(top[2] * (1 - t) + bot[2] * t)
    gd.line([(0, y), (S, y)], fill=(r, g, b, 255))
mask = Image.new("L", (S, S), 0)
ImageDraw.Draw(mask).rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, fill=255)
img.paste(grad, (0, 0), mask)

def load_font(size):
    for p in (
        "/System/Library/Fonts/SFNSRounded.ttf",
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/Library/Fonts/Arial Bold.ttf",
        "/Library/Fonts/Arial.ttf",
    ):
        try:
            return ImageFont.truetype(p, size)
        except Exception:
            continue
    return ImageFont.load_default()

def centered(text, font, cy, fill):
    box = d.textbbox((0, 0), text, font=font)
    w, h = box[2] - box[0], box[3] - box[1]
    d.text(((S - w) / 2 - box[0], cy - h / 2 - box[1]), text, font=font, fill=fill)

centered("md", load_font(440), int(S * 0.42), (255, 255, 255, 255))
centered("EPUB · PDF · WEB", load_font(78), int(S * 0.78), (219, 234, 254, 255))

img.save(out)
PY
    then
        rm -rf "$tmp"
        return 1
    fi

    local iconset="$tmp/$APP_NAME.iconset"
    mkdir -p "$iconset"
    local src="$tmp/icon_1024.png"
    for spec in "16:16x16" "32:16x16@2x" "32:32x32" "64:32x32@2x" \
                "128:128x128" "256:128x128@2x" "256:256x256" "512:256x256@2x" \
                "512:512x512" "1024:512x512@2x"; do
        local px="${spec%%:*}"; local name="${spec##*:}"
        sips -z "$px" "$px" "$src" --out "$iconset/icon_$name.png" >/dev/null 2>&1
    done
    if iconutil -c icns "$iconset" -o "$APP/Contents/Resources/$APP_NAME.icns" >/dev/null 2>&1; then
        rm -rf "$tmp"
        return 0
    fi
    rm -rf "$tmp"
    return 1
}

ICON_OK=1
if command -v python3 >/dev/null 2>&1 && make_icon python3; then
    ICON_OK=0
elif [ -x "$REPO_DIR/.venv/bin/python3" ] && make_icon "$REPO_DIR/.venv/bin/python3"; then
    ICON_OK=0
fi

# Nudge LaunchServices/Finder to refresh the icon.
touch "$APP"

echo ""
echo "✅ Built: $APP"
if [ "$ICON_OK" -ne 0 ]; then
    echo "ℹ️  No custom icon yet (Pillow not found). The app works fine with a generic icon."
    echo "    Tip: launch it once, then re-run ./make_app.sh to add the real icon."
fi

# ---------------------------------------------------------------------------
# Optional install into ~/Applications.
# ---------------------------------------------------------------------------
if [ "$1" = "--install" ]; then
    mkdir -p "$HOME/Applications"
    rm -rf "$HOME/Applications/$APP_NAME.app"
    cp -R "$APP" "$HOME/Applications/$APP_NAME.app"
    echo "✅ Installed to: $HOME/Applications/$APP_NAME.app"
fi

echo ""
echo "Next steps:"
echo "  1. Double-click epub2md.app to launch (first run sets things up automatically)."
echo "  2. Drag epub2md.app onto your Dock to keep a one-click shortcut there."
echo "  3. To stop the server: right-click the Dock icon → Quit."
